[Add] Provide code for chapter 6
PhilippKuhlmay/the-typo3-guidebook pull request #10
Opened 2021-03-03 19:54 UTC by tmfrstn

Closes #2

2021-03-04 14:08 UTC, PhilippKuhlmay commented on Ch06/Step_1/additional.txt
> +//
I suggest to add an comment here as there are the keywords for a comment. Otherwise delete the "//"

Something like "// Command for creating a ddev project"

2021-03-04 17:41 UTC, tmfrstn commented on Ch06/Step_1/additional.txt
> +//
Yes, you're right. I missed on that one.

2021-03-05 09:53 UTC, PhilippKuhlmay commented
This is now ready for review

2021-03-05 10:15 UTC, PhilippKuhlmay reviewed
I checked it and left some comments

2021-03-05 10:15 UTC, PhilippKuhlmay commented on Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html
> +<!-- Wrapper -->
I am not sure if we must include this file in step 5. This is copied from a different site. Thus this can change at the time. It makes more sense if we include it from step 6 because in step 6 its content is changed.

2021-03-05 10:15 UTC, PhilippKuhlmay commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
I would delete the <html> tag at the beginning and and. The book says "replace the content". So we should replace all the content from the code inside the book. I know the <html> is correct but it's not the same as in the book.

2021-03-05 10:15 UTC, PhilippKuhlmay commented on Ch06/all_code_from_chapter-6.txt
> +## Code Snippets from Chapter 6
Please delete this file. This doesn't match our guidelines and it is very confusing when all the code is inside one file.

2021-03-05 11:29 UTC, t3jh requested changes

2021-03-05 11:29 UTC, t3jh commented on Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html
> +<div id="wrapper">
Maybe a comment in the first line of the file would make sense: `<!-- This file is taken from the index.html of https://html5up.net/future-imperfect -->`?

2021-03-05 11:29 UTC, t3jh commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
again it must be `partialRootPaths` (without the **s** in partial**s**)

2021-03-05 11:29 UTC, t3jh commented on Ch06/Step_7/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
again: please without s

2021-03-05 11:29 UTC, t3jh commented on Ch06/Step_8/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
again: without s

2021-03-05 11:29 UTC, t3jh commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
I am not sure. In other files were the book says "Replace the content" or "Add the following code below xyz" we provide the complete file. Shouldn't we continue doing the same here?

2021-03-05 12:41 UTC, tmfrstn commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
This confused me as well. Because you copy this file from fluid_styled_content and then replace all content? Why? It would be much easier to just create it.
The only reasonI could think of was to keep the html-Tag without the need to place it in the books code..

2021-03-05 12:44 UTC, tmfrstn commented on Ch06/all_code_from_chapter-6.txt
> +## Code Snippets from Chapter 6
It's sad that there is no consent

2021-03-05 12:45 UTC, tmfrstn commented on Ch06/Step_5/site_promotiontour/Configuration/TypoScript/constants.typoscript
> +  templateRootPath = EXT:site_promotiontour/Resources/Private/Templates/Page/
Yes, my PHPStorm was wrong configured. Fixed that

2021-03-05 12:50 UTC, t3jh commented on Ch06/all_code_from_chapter-6.txt
> +## Code Snippets from Chapter 6
I find the file not bad. The reader gets all code changes from the chapter at a glance. Inside the stepXX-subfolders it is much more difficult to see what is new or changed in a file. +1 for keeping this file. By its nameit makes clear what the reader can expect there.

2021-03-05 12:57 UTC, tmfrstn commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
This is just copy and paste? Check setup vs constants

2021-03-05 12:57 UTC, tmfrstn commented on Ch06/Step_7/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
see above

2021-03-05 12:58 UTC, tmfrstn commented on Ch06/Step_8/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
see above

2021-03-05 13:04 UTC, PhilippKuhlmay commented on Ch06/all_code_from_chapter-6.txt
> +## Code Snippets from Chapter 6
Okay then I think we can keep this file.

2021-03-05 13:08 UTC, tmfrstn commented on Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html
> +<div id="wrapper">
Sounds good to me

2021-03-05 13:12 UTC, t3jh commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
Yes, the error is in the printed book, too. But I think, we should provide correct code on Github, even if it is wrong in the book itself.
In constants there is no error, just in `10.partialsRootPaths.10` (the s in partials is wrong).

2021-03-05 13:17 UTC, tmfrstn commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
**What to do here?**

2021-03-05 13:21 UTC, tmfrstn commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
Now I got it. I thought you talk about the s at the end

2021-03-05 13:26 UTC, tmfrstn commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
So this is something for errata.md too

2021-03-05 13:41 UTC, tmfrstn commented
We are nearly done. 2 decisions to make:      

**Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html**
what to do?
- delete
- replace content with comment of source
- keep as is

**Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html**
Keep or delete html Tag


Hint: errata.md -> Page 180 
10.partialsRootPaths.10 = {$page.templates.partialRootPath} (printed)
10.partialRootPaths.10 = {$page.templates.partialRootPath} (should be)

2021-03-05 13:56 UTC, PhilippKuhlmay commented on Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html
> +<!-- Wrapper -->
I suggest "Keep file and replace Content with e.g. !-- This file is taken from the index.html of https://html5up.net/future-imperfect --". So it is clear that the user can copy it from somewhere else.

2021-03-05 13:57 UTC, t3jh commented on Ch06/Step_5/site_promotiontour/Resources/Private/Templates/Page/Default.html
> +<!-- Wrapper -->
I' d say: keep the file, but add a comment in line 1 saying `<!-- This file is taken from the index.html of https://html5up.net/future-imperfect -->`

2021-03-05 13:58 UTC, PhilippKuhlmay commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
We can vote: 
keep the tag: thumps up
remove the tag: thumps down

2021-03-05 13:59 UTC, t3jh commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
My opinion: Keep the tags in beginning and end, so the file is complete. We always provide complete files, don't we?

2021-03-05 14:00 UTC, t3jh commented on Ch06/Step_6/site_promotiontour/Configuration/TypoScript/setup.typoscript
> +  10.partialsRootPaths.10 = {$page.templates.partialRootPath}
Yes, it is. We should deliver correct code here plus put it into errata.

2021-03-05 15:11 UTC, tmfrstn commented on Ch06/Step_8/site_promotiontour/Resources/Private/Layouts/ContentElements/Default.html
> +<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
I would leave it, because otherwise I don't know why I had to copy this file from fluid_styled_content.

2021-03-05 15:25 UTC, PhilippKuhlmay approved these changes

2021-03-05 15:47 UTC, t3jh approved these changes

2021-03-05 15:51 UTC, merged